version = 1.0

[default]
[default.deploy.parameters]
stack_name = "slack-bot-template"
s3_prefix = "slack-bot-template"
region = "ap-northeast-1"
confirm_changeset = false
capabilities = "CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND"
